### ISSUE TITLE
这个搞完成了以后是否需要提供独立二级域名部署？

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/rails-guides-old#1]
比如: http://rails-guides.ruby-china.org

或者 http://ruby-china.org/rails-guides

**Comment by JuanitoFatas** [comment]
+1 
http://ruby-china.org/rails-guides

**Comment by huacnlee** [comment]
这个项目是否应该改名为 rails-style-guides ? 我看好像只是风格指导。

**Comment by JuanitoFatas** [comment]
我一開始也搞混了，以為是我的那個項目，所以才留錯言XD。
這邊這個是指南。翻譯官方的 http://guides.rubyonrails.org/ 。
我翻的那個是風格指導 https://github.com/JuanitoFatas/rails-style-guide/blob/master/README-zhCN.md ^_^

**Comment by huacnlee** [comment]
我是搞错了，这个就是 Rails Guides

**Comment by Tassandar** [comment]
我觉得 guides.ruby-china.org   比较好？。手头一个盛大云到期了，这几天抽空把字体什么的调整下， 周末就开始部署 ^_^
还有华顺哥你觉的应该保持 guides的原貌么？还是可以让大家随便添加文章或者译文到 这个guides里？

**Comment by huacnlee** [comment]
保持 Guides 原貌，另外服务器这边可以有很多，盛大有赞助的，只要使用合理就行了

**Comment by Tassandar** [comment]
恩。谢了~

**Comment by Tassandar** [comment]
写了一个 cap 部署的脚本。 应该可以直接用到服务器上去了。华顺哥你看一下其他域名什么的怎么搞？
