### ISSUE TITLE
Tag 创建代码错误

### ISSUE THREAD

**Issue by alswl** [ruby-china/rails-guides-old#29]
在

> 接下来：编辑 post.rb 文件来创建来创建另一个成员，并且告诉Rails（通过 the accepts_nested_attributes_for 宏）你打算通过posts form来编辑tags。

这句话之后的代码，少了 `tags_attributes`

```
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes
```

导致 Tag 赋值错误

**Comment by Tassandar** [comment]
嗯。我 @jhjguxin 让他帮忙修改一下吧。这个初上手指南几乎每隔几天就会被更新一次。。。

**Comment by jhjguxin** [comment]
最近在忙一个新项目 各位有时间 就维护一下吧 我尽量 ...

**Comment by Tassandar** [comment]
嗯。我来吧~

**Comment by Tassandar** [comment]
改完了，3.2 新特性。多谢反馈了。
