### ISSUE TITLE
puzzle for link in guide

### ISSUE THREAD

**Issue by zlx** [ruby-china/rails-guides-old#30]
今天我在翻译active record querying一文中，发现有如下一句`"Calculations":#calculations`
但是找不到定义`#calculations`的地方，导致执行`rake generate_guides_CN`时出错了：`*** BROKEN LINK: #calculation, perhaps you meant #last_1.
*** BROKEN LINK: #calculation, perhaps you meant #last_1.
*** BROKEN LINK: #calculation, perhaps you meant #last_1.
*** BROKEN LINK: #calculation, perhaps you meant #last_1.
*** BROKEN LINK: #calculation, perhaps you meant #last_1.`

另外，我发现：
https://github.com/zlx/rails-guides/blob/master/source/CN/active_record_querying.textile#calculations
是存在的，但是源代码中没有定义：
https://raw.github.com/zlx/rails-guides/78a328eb4cf33f2708941d0072c1dca6fa749a13/source/CN/active_record_querying.textile
### 所以我想问这是不是有什么魔法在里面？？而我忽略了。

同样的问题还有
```**\* BROKEN LINK: #14, perhaps you meant #1.
**\* BROKEN LINK: #14-1, perhaps you meant #1-1.
**\* BROKEN LINK: #14-2, perhaps you meant #1-2.
**\* BROKEN LINK: #14-3, perhaps you meant #1-3.
**\* BROKEN LINK: #14-4, perhaps you meant #8-4.
**\* BROKEN LINK: #pure-string-conditions, perhaps you meant #array-range_conditions.
**\* BROKEN LINK: #joining-tables, perhaps you meant #first_1.

```
```

**Comment by zlx** [comment]
翻译了好久了，为了避免被取消，先push了

**Comment by Tassandar** [comment]
算是魔法把。。。是这样的，textile 有一个魔法 "Calculations":#calculations 的意思是Calculations 会加入 a 标签，链接到 id = calculations 的地方去。我在改写的时候发现一个问题，就是很多人会把 calculations 翻译成中文，然后标签就用不了了，所以，我就干脆把所有的标题直接改写成了数字的形式，如果出现了 **\* BROKEN LINK 的提示，我再手动地调整回来。。so~ 你就放心翻译把。。不会有什么影响的。

**Comment by zlx** [comment]
我依然不是很理解。我没翻译任何 `#calculation` ，但是还是提示错误：`*** BROKEN LINK: #calculation, perhaps you meant #last_1.`
从这个提示看来，是找不到 `#calculation` 的链接，事实上的确没有明确定义 `id=calculation` 的地方。

**Comment by zlx** [comment]
我依然不是很理解。我没翻译任何 #calculation ，但是还是提示错误：**\* BROKEN LINK: #calculation,
perhaps you meant #last_1.
从这个提示看来，是找不到 #calculation 的链接，事实上的确没有明确定义 id=calculation 的地方。

2012/6/26 Tassandar <
reply@reply.github.com

**Comment by Tassandar** [comment]
**\* BROKEN LINK:   仅仅是一个提示，并不影响任何使用。 可能是别的文章指出了 #calculation, 但是找不到对应的标签。

**Comment by zlx** [comment]
好的，我现在知道了，原来在生成html时候所有的标题都会赋予一个数字的id值，原先要链接给这个标题的要修改成对应的数字就可以了。
