### ISSUE TITLE
github页面的description的translation拼错了

### ISSUE THREAD

**Issue by cxyokk** [ruby-china/rails-guides-old#87]
RT，就是在[https://github.com/ruby-china/rails-guides](https://github.com/ruby-china/rails-guides)这个页面的顶部，那句description：`A Ruby on Rails Traslation Guide`，里面的`traslation`应为`translation`。

**Comment by cxyokk** [comment]
那句description是不是叫`Rails Guides in Chinese`或者直接叫`Ruby on Rails Guides 中文指南`好一点？

另外，[http://guides.ruby-china.org](http://guides.ruby-china.org)这个url打不开了，不知道迁移到什么地方了？

**Comment by JuanitoFatas** [comment]
@cxyokk 新的代码仓库 :point_right:  https://github.com/ruby-china/guides
