### ISSUE TITLE
与 Rails 的第一次接触

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby-china/rails-guides-old#9]
目录与英文版不符。。。

**Comment by Tassandar** [comment]
恩，我也觉得 《Rails 上手指南》 可能好一点。

**Comment by JuanitoFatas** [comment]
@Tassandar 不是，我的意思是右邊的目錄編號與英文版的對不起來。

**Comment by Tassandar** [comment]
哦，我也发现了，貌似文章查挺多，可能是因为当时翻译的是3.0版本的 getting started ，我让原译者帮忙维护一下吧。
